const QUALITIES = [
  { category: 'quality', name: 'Злой' },
  { category: 'quality', name: 'Добрый' },
  { category: 'quality', name: 'Вежливый' },
  { category: 'quality', name: 'Культурный' },
  { category: 'quality', name: 'Харизматичный' },

  { category: 'quality', name: 'Дружелюбный' },
  { category: 'quality', name: 'Капризный' },
  { category: 'quality', name: 'Открытый' },
  { category: 'quality', name: 'Безумный' },
  { category: 'quality', name: 'Жизнерадостный' },

  { category: 'quality', name: 'Осторожный' },
  { category: 'quality', name: 'Безнадёжный' },
  { category: 'quality', name: 'Заботливый' },
  { category: 'quality', name: 'Смышлённый' },
  { category: 'quality', name: 'Флегматик' },

  { category: 'quality', name: 'Асоциальный' },
  { category: 'quality', name: 'Благоразумный' },
  { category: 'quality', name: 'Безотказный' },
  { category: 'quality', name: 'Деятельный' },
  { category: 'quality', name: 'Авторитетный' },

  { category: 'quality', name: 'Вдумчивый' },
  { category: 'quality', name: 'Гениальный' },
  { category: 'quality', name: 'Угрюмый' },
  { category: 'quality', name: 'Депрессивный' },
  { category: 'quality', name: 'Меланхоличный' },

  { category: 'quality', name: 'Нервный' },
  { category: 'quality', name: 'Боязливый' },
  { category: 'quality', name: 'Агрессивный' },
  { category: 'quality', name: 'Спокойный' },
  { category: 'quality', name: 'Скупой' },

  { category: 'quality', name: 'Грубый' },
  { category: 'quality', name: 'Строгий' },
  { category: 'quality', name: 'Терпеливый' },
  { category: 'quality', name: 'Мужественный' },
  { category: 'quality', name: 'Смелый' },

  { category: 'quality', name: 'Сильный' },
  { category: 'quality', name: 'Жадный' },
  { category: 'quality', name: 'Раздражительный' },
  { category: 'quality', name: 'Скандальный' },
  { category: 'quality', name: 'Конфликтный' },

  { category: 'quality', name: 'Нудный' },
  { category: 'quality', name: 'Пошлый' },
  { category: 'quality', name: 'Алчный' },
  { category: 'quality', name: 'Ленивый' },
  { category: 'quality', name: 'Тупой' },

  { category: 'quality', name: 'Глупый' },
  { category: 'quality', name: 'Наглый' },
  { category: 'quality', name: 'Жестокий' },
  { category: 'quality', name: 'Серьезный' },
  { category: 'quality', name: 'Человечный' },

  { category: 'quality', name: 'Эстет' },
  { category: 'quality', name: 'Самовлюбленный' },
  { category: 'quality', name: 'Самоуверенный' },
  { category: 'quality', name: 'Жалкий' },
  { category: 'quality', name: 'Бдительный' },

  { category: 'quality', name: 'Застенчивый' },
  { category: 'quality', name: 'Надежный' },
  { category: 'quality', name: 'Безынитициативный' },
  { category: 'quality', name: 'Осторожный' },
  { category: 'quality', name: 'Веселый' },

  { category: 'quality', name: 'Любезный' },
  { category: 'quality', name: 'Гостеприимный' },
  { category: 'quality', name: 'Скептик' },
  { category: 'quality', name: 'Приветливый' },
  { category: 'quality', name: 'Опрятный' },

  { category: 'quality', name: 'Ворчливый' },
  { category: 'quality', name: 'Понимающий' },
  { category: 'quality', name: 'Отважный' },
  { category: 'quality', name: 'Двуличный' },
  { category: 'quality', name: 'Благоразумный' },

  { category: 'quality', name: 'Внимательный' },
  { category: 'quality', name: 'Наблюдательный' },
  { category: 'quality', name: 'Вальяжный' },
  { category: 'quality', name: 'Подлый' },
  { category: 'quality', name: 'Предприимчивый' },

  { category: 'quality', name: 'Умный' },
  { category: 'quality', name: 'Терпеливый' },
  { category: 'quality', name: 'Начитанный' },
  { category: 'quality', name: 'Мизантроп' },
  { category: 'quality', name: 'Грубиян' },

  { category: 'quality', name: 'Мудрый' },
  { category: 'quality', name: 'Грубиян' },
  { category: 'quality', name: 'Трусливый' },
  { category: 'quality', name: 'Фанатист' },
  { category: 'quality', name: 'Неопрятный' },

  { category: 'quality', name: 'Задорный' },
  { category: 'quality', name: 'Волевой' },
  { category: 'quality', name: 'Параноик' },
  { category: 'quality', name: 'Любвиобильный' },
  { category: 'quality', name: 'Собранный' },
];

export const generateCards = () => QUALITIES;
